#index:
#    path: /
#    controller: App\Controller\DefaultController::index

#wild_show_index:
#    path: /wild/
#    controller: App\Controller\WildController::index

#wild_default_index:
#    path: /
#    controller: App\Controller\DefaultController::index

#wild_show_show:
#    path: /wild/show/{slug}
#    controller: App\Controller\WildController::show
